# Generated by Django 5.0.6 on 2024-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_base', '0002_buyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
